// Next
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

// tRPC
import { api } from "~/utils/api";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Hyrule Help</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen items-center justify-center">
        <div className="card glass relative z-10 mx-auto max-w-lg">
          <div className="card-body">
            <h1 className="mb-4 text-center text-5xl font-bold">Hyrule Help</h1>
            <p className="mb-4">
              Get answers to your questions on your favorite game.
            </p>
            <Link href="/questions" className="btn-primary btn">
              View Questions
            </Link>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
